// codepetTests/DiffPatchTests.swift
import XCTest
@testable import codepet

/// The unified-diff parser behind the Review pane.
///
/// The line NUMBERS are the part worth testing hardest. Inline comments are the
/// first thing after freeze and attach to `file:line`, so a number that is off
/// by one puts a founder's comment on the wrong line of their own code —
/// silently, and only discoverable by reading the result.
final class DiffPatchTests: XCTestCase {

    func testAnEmptyOrMissingPatchIsNoLines() {
        // A binary file has no patch. The pane renders the row without a body.
        XCTAssertTrue(DiffPatch.parse(nil).isEmpty)
        XCTAssertTrue(DiffPatch.parse("").isEmpty)
    }

    func testReadsTheStartingLineNumbersFromTheHunkHeader() {
        let (old, new) = try! XCTUnwrap(DiffPatch.parseHunkHeader("@@ -12,7 +34,9 @@ func thing() {"))
        XCTAssertEqual(old, 12)
        XCTAssertEqual(new, 34)
    }

    func testAHeaderWithNoCountsStillParses() {
        // `@@ -1 +1 @@` is legal for a single-line hunk.
        let (old, new) = try! XCTUnwrap(DiffPatch.parseHunkHeader("@@ -1 +1 @@"))
        XCTAssertEqual(old, 1)
        XCTAssertEqual(new, 1)
    }

    func testAnUnparseableHeaderStillRendersARowRatherThanEmptyingThePane() {
        // A patch is generated by another system. One header we cannot read must
        // not cost the founder the whole diff.
        let lines = DiffPatch.parse("@@ nonsense @@\n context")
        XCTAssertEqual(lines.first?.kind, .hunk)
        XCTAssertEqual(lines.count, 2)
    }

    func testNumbersAdvanceCorrectlyThroughAMixedHunk() {
        // The core case. An added line advances only the NEW side, a removed
        // line only the OLD side, context advances both.
        let patch = """
        @@ -10,3 +10,4 @@
         unchanged
        -gone
        +new one
        +new two
         after
        """
        let lines = DiffPatch.parse(patch)
        XCTAssertEqual(lines.map(\.kind), [.hunk, .context, .removed, .added, .added, .context])
        // old: 10 context, 11 removed, then 12 after
        XCTAssertEqual(lines[1].oldLine, 10)
        XCTAssertEqual(lines[2].oldLine, 11)
        XCTAssertNil(lines[3].oldLine, "an added line does not exist in the old file")
        XCTAssertEqual(lines[5].oldLine, 12)
        // new: 10 context, 11 and 12 added, then 13 after
        XCTAssertEqual(lines[1].newLine, 10)
        XCTAssertNil(lines[2].newLine, "a removed line does not exist in the new file")
        XCTAssertEqual(lines[3].newLine, 11)
        XCTAssertEqual(lines[4].newLine, 12)
        XCTAssertEqual(lines[5].newLine, 13)
    }

    func testASecondHunkRestartsFromItsOwnHeader() {
        // Without this the second hunk's numbers continue from the first and
        // every line in it is wrong by the size of the gap.
        let patch = """
        @@ -1,2 +1,2 @@
         a
        @@ -50,2 +60,2 @@
         b
        """
        let lines = DiffPatch.parse(patch)
        XCTAssertEqual(lines[1].newLine, 1)
        XCTAssertEqual(lines[3].oldLine, 50)
        XCTAssertEqual(lines[3].newLine, 60)
    }

    func testTheNoNewlineMarkerIsNotCountedAsALine() {
        // "\\ No newline at end of file" is a note about the line above it.
        // Counting it shifts every number after it by one.
        let patch = """
        @@ -1,2 +1,2 @@
        -old
        \\ No newline at end of file
        +new
        """
        let lines = DiffPatch.parse(patch)
        let marker = lines[2]
        XCTAssertNil(marker.oldLine)
        XCTAssertNil(marker.newLine)
        XCTAssertEqual(lines[3].newLine, 1, "the marker consumed a line number it should not have")
    }

    func testTheTextExcludesThePrefixMarker() {
        // The +/- belongs to the gutter, not the code. Leaving it in the text
        // means every line renders shifted one column against its neighbours.
        let lines = DiffPatch.parse("@@ -1 +1 @@\n+const x = 1")
        XCTAssertEqual(lines[1].text, "const x = 1")
    }

    func testAnEmptyAddedLineKeepsItsPlace() {
        // A blank line added to a file is a real change and a real line number.
        let lines = DiffPatch.parse("@@ -1,1 +1,2 @@\n a\n+")
        XCTAssertEqual(lines.count, 3)
        XCTAssertEqual(lines[2].kind, .added)
        XCTAssertEqual(lines[2].text, "")
        XCTAssertEqual(lines[2].newLine, 2)
    }

    // MARK: - the anchor a future comment attaches to

    func testTheCommentAnchorPrefersTheNewFileLine() {
        let lines = DiffPatch.parse("@@ -5,1 +7,1 @@\n+added")
        XCTAssertEqual(lines[1].commentAnchor, 7)
    }

    func testARemovedLineAnchorsToItsOldNumber() {
        // A comment on a deleted line is a real thing to want to say, and the
        // only number it can have is the pre-change one.
        let lines = DiffPatch.parse("@@ -5,1 +7,0 @@\n-gone")
        XCTAssertEqual(lines[1].commentAnchor, 5)
    }

    func testAHunkHeaderHasNoAnchorBecauseItIsNotALineOfTheFile() {
        let lines = DiffPatch.parse("@@ -1,1 +1,1 @@\n a")
        XCTAssertNil(lines[0].commentAnchor)
        XCTAssertEqual(lines[1].commentAnchor, 1)
    }

    func testEveryRealLineHasAnAnchor() {
        // The property inline comments depend on: if any renderable line lacks a
        // number, a comment on it has nowhere to attach.
        let patch = """
        @@ -1,3 +1,3 @@
         context
        -removed
        +added
        """
        for line in DiffPatch.parse(patch) where line.kind != .hunk {
            XCTAssertNotNil(line.commentAnchor, "\(line.kind) line has no anchor: \(line.text)")
        }
    }

    func testIdsAreUniqueSoRowsDoNotCollapseInAList() {
        // Two hunks can repeat a line number after a jump; ids must not.
        let patch = "@@ -1,1 +1,1 @@\n a\n@@ -1,1 +1,1 @@\n a"
        let ids = DiffPatch.parse(patch).map(\.id)
        XCTAssertEqual(Set(ids).count, ids.count)
    }
}
