import SwiftUI

/// Card shown at the top of a project's session list. Two sections:
///   1. **Description** — editable user-written project description
///   2. **Activity Log** — auto-generated changelog entries (read-only, collapsible)
///
/// The brief string is split on the first `\n\n---\n` separator. Everything
/// before it is the user's description; everything from that point on is the
/// changelog generated by `SessionSummaryEnricher`.
struct ProjectBriefCard: View {
    let projectPath: String
    @EnvironmentObject var projectStore: ProjectStore
    @EnvironmentObject var interviewCoordinator: InterviewCoordinator
    @Environment(\.uiLanguage) private var uiLanguage

    @State private var briefText: String = ""
    @State private var savedConfirmation: Date? = nil
    @State private var isEditing = false
    @State private var logExpanded = false

    private var project: Project? {
        projectStore.project(for: projectPath)
    }

    /// Split the stored brief into user description + changelog entries.
    private var briefParts: (description: String, changelog: [String]) {
        let raw = project?.brief ?? ""
        let separator = "\n\n---\n"
        guard let firstSep = raw.range(of: separator) else {
            return (raw.trimmingCharacters(in: .whitespacesAndNewlines), [])
        }
        let desc = String(raw[raw.startIndex..<firstSep.lowerBound])
            .trimmingCharacters(in: .whitespacesAndNewlines)
        let logSection = String(raw[firstSep.lowerBound...])
        let entries = logSection
            .components(separatedBy: separator)
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty }
        return (desc, entries)
    }

    private var hasDescription: Bool {
        !briefParts.description.isEmpty
    }

    private var hasChangelog: Bool {
        !briefParts.changelog.isEmpty
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            // MARK: Header
            headerRow

            // MARK: Description section
            descriptionSection
                .padding(.top, 10)

            // MARK: Activity log section
            if hasChangelog {
                activityLogSection
                    .padding(.top, 12)
            }
        }
        .padding(16)
        .frame(maxWidth: .infinity, alignment: .leading)
        // Thin 2px accent border + subtle shadow, matching the Profile page boxes
        // (not the heavy black 4px default).
        .pixelBox(fill: ReflectionTheme.cardBackground,
                  borderColor: ReflectionTheme.accent,
                  shadowOffset: 2, blockSize: 2, steps: 2, borderWidth: 2)
        .onAppear {
            briefText = briefParts.description
        }
    }

    // MARK: - Header

    private var headerRow: some View {
        HStack(spacing: 8) {
            Image(systemName: "folder.fill")
                .font(.system(size: 14))
                .foregroundColor(ReflectionTheme.accent)
            Text(project?.displayName ?? Project.nameFromPath(projectPath))
                .font(ReflectionTheme.sans(14, weight: .semibold))
                .foregroundColor(ReflectionTheme.primaryText)
            Spacer()
            // Guided founder-brief interview. Shown only when this project has no
            // structured brief yet (the coordinator's request(_:) is gated the same
            // way, so it opens the interview sheet at the app root).
            if project?.companyBrief == nil, let p = project {
                Button {
                    interviewCoordinator.request(p)
                } label: {
                    HStack(spacing: 4) {
                        Image(systemName: "sparkles")
                            .font(.system(size: 11))
                        Text(uiLanguage == .vi ? "Thiết lập có hướng dẫn" : "Guided setup")
                            .font(ReflectionTheme.sans(11, weight: .medium))
                    }
                    .foregroundColor(ReflectionTheme.accent)
                }
                .buttonStyle(.plain)
                .padding(.trailing, hasDescription && !isEditing ? 10 : 0)
            }
            if hasDescription && !isEditing {
                Button {
                    briefText = briefParts.description
                    isEditing = true
                } label: {
                    Text(uiLanguage == .vi ? "Chỉnh sửa" : "Edit")
                        .font(ReflectionTheme.sans(11, weight: .medium))
                        .foregroundColor(ReflectionTheme.accent)
                }
                .buttonStyle(.plain)
            }
        }
    }

    // MARK: - Description

    @ViewBuilder
    private var descriptionSection: some View {
        if hasDescription && !isEditing {
            Text(briefParts.description)
                .font(ReflectionTheme.sans(12.5))
                .foregroundColor(ReflectionTheme.secondaryText)
                .lineSpacing(2)
                .fixedSize(horizontal: false, vertical: true)
        } else {
            // Prompt or edit mode
            Text(uiLanguage == .vi
                 ? "Mô tả ngắn về dự án này để pet hiểu bối cảnh tốt hơn."
                 : "Describe this project briefly so your pet can give you better context.")
                .font(ReflectionTheme.sans(12))
                .foregroundColor(ReflectionTheme.mutedText)

            TextEditor(text: $briefText)
                .font(ReflectionTheme.sans(12.5))
                .foregroundColor(ReflectionTheme.primaryText)
                .scrollContentBackground(.hidden)
                .frame(minHeight: 60, maxHeight: 100)
                .padding(8)
                .background(
                    RoundedRectangle(cornerRadius: 6)
                        .fill(Color.white.opacity(0.6))
                )
                .overlay(
                    RoundedRectangle(cornerRadius: 6)
                        .stroke(ReflectionTheme.borderLight, lineWidth: 1)
                )

            saveRow
        }
    }

    // MARK: - Save row

    private var saveRow: some View {
        HStack(spacing: 8) {
            Button { saveBrief() } label: {
                Text(uiLanguage == .vi ? "Lưu" : "Save")
                    .font(ReflectionTheme.sans(12, weight: .medium))
                    .foregroundColor(.white)
                    .padding(.horizontal, 14)
                    .padding(.vertical, 6)
                    .background(Capsule().fill(ReflectionTheme.accent))
            }
            .buttonStyle(.plain)
            .disabled(briefText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)
            .opacity(briefText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ? 0.5 : 1.0)

            if isEditing {
                Button {
                    isEditing = false
                } label: {
                    Text(uiLanguage == .vi ? "Hủy" : "Cancel")
                        .font(ReflectionTheme.sans(12, weight: .medium))
                        .foregroundColor(ReflectionTheme.mutedText)
                }
                .buttonStyle(.plain)
            }

            if let until = savedConfirmation, until > Date() {
                HStack(spacing: 4) {
                    Image(systemName: "checkmark.circle.fill")
                        .foregroundColor(ReflectionTheme.moodCalm)
                    Text(uiLanguage == .vi ? "Đã lưu" : "Saved")
                        .font(ReflectionTheme.sans(11, weight: .medium))
                        .foregroundColor(ReflectionTheme.secondaryText)
                }
                .transition(.opacity)
            }
            Spacer()
        }
    }

    // MARK: - Activity Log

    private var activityLogSection: some View {
        VStack(alignment: .leading, spacing: 8) {
            // Separator
            Rectangle()
                .fill(ReflectionTheme.borderLight)
                .frame(height: 1)

            // Toggle header
            Button {
                withAnimation(.easeInOut(duration: 0.2)) {
                    logExpanded.toggle()
                }
            } label: {
                HStack(spacing: 6) {
                    Image(systemName: "clock.arrow.circlepath")
                        .font(.system(size: 11))
                        .foregroundColor(ReflectionTheme.mutedText)
                    Text(uiLanguage == .vi
                         ? "Nhật ký hoạt động (\(briefParts.changelog.count))"
                         : "Activity log (\(briefParts.changelog.count))")
                        .font(ReflectionTheme.sans(11, weight: .medium))
                        .foregroundColor(ReflectionTheme.mutedText)
                    Spacer()
                    Image(systemName: logExpanded ? "chevron.up" : "chevron.down")
                        .font(.system(size: 10, weight: .medium))
                        .foregroundColor(ReflectionTheme.mutedText)
                }
            }
            .buttonStyle(.plain)

            if logExpanded {
                VStack(alignment: .leading, spacing: 6) {
                    // Show entries in reverse chronological order (newest first)
                    ForEach(Array(briefParts.changelog.reversed().enumerated()), id: \.offset) { _, entry in
                        changelogEntry(entry)
                    }
                }
                .transition(.opacity.combined(with: .move(edge: .top)))
            }
        }
    }

    private func changelogEntry(_ entry: String) -> some View {
        HStack(alignment: .top, spacing: 8) {
            Circle()
                .fill(ReflectionTheme.accent.opacity(0.3))
                .frame(width: 6, height: 6)
                .padding(.top, 5)
            Text(markdown: entry)
                .font(ReflectionTheme.sans(11.5))
                .foregroundColor(ReflectionTheme.secondaryText)
                .lineSpacing(1.5)
                .fixedSize(horizontal: false, vertical: true)
        }
    }

    // MARK: - Save

    /// Saves only the user-written description, preserving the changelog.
    private func saveBrief() {
        let trimmedDesc = briefText.trimmingCharacters(in: .whitespacesAndNewlines)
        let changelog = briefParts.changelog
        var fullBrief = trimmedDesc
        if !changelog.isEmpty {
            for entry in changelog {
                fullBrief += "\n\n---\n\(entry)"
            }
        }
        projectStore.updateBrief(projectId: projectPath, brief: fullBrief)
        // The user hand-edited the description: it is now theirs, so the
        // from-history synthesis must never overwrite it.
        projectStore.markBriefUserOwned(projectPath: projectPath)
        isEditing = false
        withAnimation(.easeInOut(duration: 0.2)) {
            savedConfirmation = Date().addingTimeInterval(2)
        }
        DispatchQueue.main.asyncAfter(deadline: .now() + 2.1) {
            withAnimation(.easeInOut(duration: 0.2)) {
                if let until = savedConfirmation, until <= Date() {
                    savedConfirmation = nil
                }
            }
        }
    }
}
